<?php

namespace App\Models;

use CodeIgniter\Model;

class BillingInvoiceModel extends Model
{
    protected $table = 't_invoice';
    protected $primaryKey = 'invoice_id';
    protected $useAutoIncrement = true;
    protected $returnType = 'array';
    protected $useSoftDeletes = false;
    protected $protectFields = true;
    protected $allowedFields = [
        'school_id',
        'student_id',
        'subscription_id',
        'invoice_no',
        'status',
        'issue_date',
        'due_date',
        'currency',
        'subtotal_cents',
        'tax_cents',
        'late_fee_cents',
        'discount_cents',
        'total_cents',
        'balance_cents',
        'meta_json',
    ];

    // Dates
    protected $useTimestamps = true;
    protected $dateFormat = 'datetime';
    protected $createdField = 'created_at';
    protected $updatedField = 'updated_at';

    // Validation
    protected $validationRules = [
        'school_id' => 'required|integer',
        'student_id' => 'required|integer',
        'invoice_no' => 'permit_empty|max_length[40]', // Auto-generated by beforeInsert callback
        'status' => 'permit_empty|in_list[draft,open,paid,voided,failed,past_due]',
        'issue_date' => 'required|valid_date',
        'due_date' => 'required|valid_date',
        'currency' => 'permit_empty|exact_length[3]',
        'total_cents' => 'required|integer',
    ];

    protected $validationMessages = [
        'school_id' => [
            'required' => 'School ID is required',
        ],
        'student_id' => [
            'required' => 'Student ID is required',
        ],
    ];

    protected $skipValidation = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks = true;
    protected $beforeInsert = ['generateInvoiceNumber'];
    protected $afterInsert = [];
    protected $beforeUpdate = [];
    protected $afterUpdate = [];

    /**
     * Generate invoice number before insert
     */
    protected function generateInvoiceNumber(array $data): array
    {
        if (!empty($data['data']['invoice_no'])) {
            return $data;
        }

        $schoolId = $data['data']['school_id'] ?? null;
        if (!$schoolId) {
            return $data;
        }

        // Get school short code
        $db = \Config\Database::connect();
        $school = $db->table('school')->where('school_id', $schoolId)->get()->getRowArray();
        $schoolShort = $school['school_short_name'] ?? ($school['short_code'] ?? 'SCH' . $schoolId);

        // Get current year
        $year = date('y');

        // Get next sequence for this school and year
        $prefix = "INV-{$schoolShort}-{$year}-";

        // Use database query builder instead of model to avoid conflicts during insert
        $lastInvoice = $db->table('t_invoice')
            ->where('school_id', $schoolId)
            ->like('invoice_no', $prefix, 'after')
            ->orderBy('invoice_id', 'DESC')
            ->get()
            ->getRowArray();

        $sequence = 1;
        if ($lastInvoice) {
            $lastSeq = (int) str_replace($prefix, '', $lastInvoice['invoice_no']);
            $sequence = $lastSeq + 1;
        }

        $data['data']['invoice_no'] = $prefix . str_pad($sequence, 5, '0', STR_PAD_LEFT);

        return $data;
    }

    /**
     * Get invoices by school with filters
     */
    public function getBySchool(int $schoolId, array $filters = [], int $limit = 50, int $offset = 0): array
    {
        $builder = $this->where('school_id', $schoolId);

        if (!empty($filters['status'])) {
            if (is_array($filters['status'])) {
                $builder->whereIn('status', $filters['status']);
            } else {
                $builder->where('status', $filters['status']);
            }
        }

        if (!empty($filters['student_id'])) {
            $builder->where('student_id', $filters['student_id']);
        }

        if (!empty($filters['subscription_id'])) {
            $builder->where('subscription_id', $filters['subscription_id']);
        }

        if (!empty($filters['due_from'])) {
            $builder->where('due_date >=', $filters['due_from']);
        }

        if (!empty($filters['due_to'])) {
            $builder->where('due_date <=', $filters['due_to']);
        }

        if (!empty($filters['search'])) {
            $builder->groupStart()
                ->like('invoice_no', $filters['search'])
                ->orWhere('student_id IN (SELECT user_id FROM user WHERE full_name LIKE "%' . $filters['search'] . '%")')
                ->groupEnd();
        }

        return $builder->orderBy('invoice_id', 'DESC')
            ->findAll($limit, $offset);
    }

    /**
     * Get invoice with full details (items, payments, student info)
     */
    public function getWithDetails(int $invoiceId): ?array
    {
        // Fixed: Join with user_profile table for student name, and use email_id from user table
        $invoice = $this->select("t_invoice.*,
                                   CONCAT(user_profile.first_name, ' ', user_profile.last_name) as student_name,
                                   user.email_id as student_email")
            ->join('user', 'user.user_id = t_invoice.student_id', 'left')
            ->join('user_profile', 'user_profile.user_id = t_invoice.student_id', 'left')
            ->where('t_invoice.invoice_id', $invoiceId)
            ->first();

        if (!$invoice) {
            return null;
        }

        // Get invoice items
        $itemModel = new InvoiceItemModel();
        $invoice['items'] = $itemModel->where('invoice_id', $invoiceId)->findAll();

        // Get payment transactions
        $paymentModel = new PaymentTxnModel();
        $invoice['payments'] = $paymentModel->where('invoice_id', $invoiceId)
            ->orderBy('created_at', 'DESC')
            ->findAll();

        return $invoice;
    }

    /**
     * Get overdue invoices
     */
    public function getOverdue(int $schoolId, string $asOfDate = null): array
    {
        $date = $asOfDate ?? date('Y-m-d');

        return $this->where('school_id', $schoolId)
            ->whereIn('status', ['open', 'past_due'])
            ->where('due_date <', $date)
            ->where('balance_cents >', 0)
            ->orderBy('due_date', 'ASC')
            ->findAll();
    }

    /**
     * Get invoices due soon
     */
    public function getDueSoon(int $schoolId, int $days = 7): array
    {
        $today = date('Y-m-d');
        $futureDate = date('Y-m-d', strtotime("+{$days} days"));

        return $this->where('school_id', $schoolId)
            ->where('status', 'open')
            ->where('due_date >=', $today)
            ->where('due_date <=', $futureDate)
            ->where('balance_cents >', 0)
            ->orderBy('due_date', 'ASC')
            ->findAll();
    }

    /**
     * Update invoice status
     */
    public function updateStatus(int $invoiceId, string $status): bool
    {
        $validStatuses = ['draft', 'open', 'paid', 'voided', 'failed', 'past_due'];
        if (!in_array($status, $validStatuses)) {
            return false;
        }

        return $this->update($invoiceId, ['status' => $status]);
    }

    /**
     * Apply payment to invoice
     */
    public function applyPayment(int $invoiceId, int $amountCents): bool
    {
        $invoice = $this->find($invoiceId);
        if (!$invoice) {
            return false;
        }

        $newBalance = $invoice['balance_cents'] - $amountCents;
        $newStatus = $newBalance <= 0 ? 'paid' : $invoice['status'];

        return $this->update($invoiceId, [
            'balance_cents' => max(0, $newBalance),
            'status' => $newStatus,
        ]);
    }

    /**
     * Add late fee to invoice
     */
    public function addLateFee(int $invoiceId, int $lateFeeAmountCents): bool
    {
        $invoice = $this->find($invoiceId);
        if (!$invoice) {
            return false;
        }

        $newLateFee = $invoice['late_fee_cents'] + $lateFeeAmountCents;
        $newTotal = $invoice['total_cents'] + $lateFeeAmountCents;
        $newBalance = $invoice['balance_cents'] + $lateFeeAmountCents;

        return $this->update($invoiceId, [
            'late_fee_cents' => $newLateFee,
            'total_cents' => $newTotal,
            'balance_cents' => $newBalance,
            'status' => 'past_due',
        ]);
    }

    /**
     * Void invoice
     */
    public function voidInvoice(int $invoiceId): bool
    {
        return $this->update($invoiceId, [
            'status' => 'voided',
            'balance_cents' => 0,
        ]);
    }

    /**
     * Recompute invoice totals from items
     */
    public function recomputeTotals(int $invoiceId): bool
    {
        $itemModel = new InvoiceItemModel();
        $items = $itemModel->where('invoice_id', $invoiceId)->findAll();

        $subtotal = 0;
        $tax = 0;
        $lateFee = 0;

        foreach ($items as $item) {
            if ($item['type'] === 'tax') {
                $tax += $item['line_total_cents'];
            } elseif ($item['type'] === 'late_fee') {
                $lateFee += $item['line_total_cents'];
            } else {
                $subtotal += $item['line_total_cents'];
            }
        }

        $total = $subtotal + $tax + $lateFee;

        return $this->update($invoiceId, [
            'subtotal_cents' => $subtotal,
            'tax_cents' => $tax,
            'late_fee_cents' => $lateFee,
            'total_cents' => $total,
            'balance_cents' => $total, // Assumes no prior payments
        ]);
    }

    /**
     * Get invoice statistics for school
     */
    public function getStats(int $schoolId): array
    {
        $stats = [
            'total' => 0,
            'open' => 0,
            'past_due' => 0,
            'paid' => 0,
            'total_outstanding_cents' => 0,
        ];

        $results = $this->select('status, COUNT(*) as count, SUM(balance_cents) as total_balance')
            ->where('school_id', $schoolId)
            ->groupBy('status')
            ->findAll();

        foreach ($results as $row) {
            $stats['total'] += $row['count'];
            $stats[$row['status']] = $row['count'];

            if (in_array($row['status'], ['open', 'past_due'])) {
                $stats['total_outstanding_cents'] += $row['total_balance'] ?? 0;
            }
        }

        return $stats;
    }
}
